// examples/react/src/views/Uploader/index.jsx
import CanvasElement from './Canvas';
import SelectFile from './SelectFile';
import WithInput from './WithInput';

const View = () => {
  return (
    <div className="responsive">
      <SelectFile />
      <CanvasElement />
      <WithInput fileFormat="File" />
      <WithInput fileFormat="Blob" />
      <WithInput fileFormat="Base64" />
      <WithInput fileFormat="ArrayBuffer" />
    </div>
  );
};

export default View;

// examples/svelte/src/views/Uploader/index.svelte
<script>
import CanvasElement from './Canvas';
import SelectFile from './SelectFile';
import WithInput from './WithInput';
</script>

<div class="responsive">
  <SelectFile></SelectFile>
  <CanvasElement></CanvasElement>
  <WithInput fileFormat="File"></WithInput>
  <WithInput fileFormat="Blob"></WithInput>
  <WithInput fileFormat="Base64"></WithInput>
  <WithInput fileFormat="ArrayBuffer"></WithInput>
</div>
