// examples/vue/src/views/FormHook/index.vue
<template>
  <div class="responsive">
    <store-form></store-form>
    <edit-form></edit-form>
    <multi-form></multi-form>
    <condition-filter></condition-filter>
  </div>
</template>

<script setup>
import ConditionFilter from './ConditionFilter';
import EditForm from './EditForm';
import MultiForm from './MultiForm';
import StoreForm from './StoreForm';
</script>

// examples/react/src/views/FormHook/index.jsx
import ConditionFilter from './ConditionFilter';
import EditForm from './EditForm';
import MultiForm from './MultiForm';
import StoreForm from './StoreForm';

function View() {
  return (
    <div className="responsive">
      <StoreForm></StoreForm>
      <EditForm></EditForm>
      <MultiForm></MultiForm>
      <ConditionFilter></ConditionFilter>
    </div>
  );
}

export default View;
