// examples/react/src/views/AutoRequest/PageFocus.jsx
import { useAutoRequest } from 'alova/client';
import { useState } from 'react';
import { getLatestTime } from '../../api/methods';
import FileViewer from '../../components/FileViewer';

function PageFocus() {
  const [isStop, setIsStop] = useState(false);
  const { loading, data } = useAutoRequest(getLatestTime, {
    enableNetwork: false,
    enableVisibility: false,
    enableFocus: true,
    middleware(_, next) {
      if (isStop) {
        return;
      }
      next();
    }
  });

  return (
    <div className="grid gap-y-4">
      <FileViewer
        filePath={window.__page.source[3]}
        docPath={window.__page.doc}>
        <nord-banner variant="success">Toggle your browser page tabs</nord-banner>
      </FileViewer>
      <nord-button
        onClick={() => setIsStop(!isStop)}
        variant="primary">
        <nord-icon
          class="mr-2"
          name={isStop ? 'interface-play' : 'interface-pause'}></nord-icon>
        {isStop ? 'Start Request' : 'Stop Request'}
      </nord-button>
      <div className="flex">
        <span>Refresh Time: {data || '--'}</span>
        {loading ? <nord-spinner /> : null}
      </div>
    </div>
  );
}

export default PageFocus;

// examples/svelte/src/views/AutoRequest/PageFocus.svelte
<script>
  import { useAutoRequest } from 'alova/client';
  import { getLatestTime } from '../../api/methods';
  import FileViewer from '../../components/FileViewer.svelte';

  const filePath = window.__page.source[2];
  const docPath = window.__page.doc;
  let isStop = false;
  const { loading, data } = useAutoRequest(getLatestTime, {
    enableNetwork: false,
    enableVisibility: false,
    enableFocus: true,
    middleware(_, next) {
      if (!isStop) {
        next();
      }
    }
  });

  const toggleStop = () => {
    isStop = !isStop;
  };
</script>

<div class="grid gap-y-4">
  <FileViewer
    {filePath}
    {docPath}>
    <nord-banner variant="success">Toggle your browser page tabs</nord-banner>
  </FileViewer>
  <nord-button
    on:click={toggleStop}
    variant="primary">
    <nord-icon
      class="mr-2"
      name={isStop ? 'interface-play' : 'interface-pause'} />
    {isStop ? 'Start Request' : 'Stop Request'}
  </nord-button>
  <div class="flex">
    <span>Refresh Time: {$data || '--'}</span>
    {#if $loading}
      <nord-spinner />
    {/if}
  </div>
</div>
