// examples/svelte/src/views/Uploader/index.svelte
<script>
import CanvasElement from './Canvas';
import SelectFile from './SelectFile';
import WithInput from './WithInput';
</script>

<div class="responsive">
  <SelectFile></SelectFile>
  <CanvasElement></CanvasElement>
  <WithInput fileFormat="File"></WithInput>
  <WithInput fileFormat="Blob"></WithInput>
  <WithInput fileFormat="Base64"></WithInput>
  <WithInput fileFormat="ArrayBuffer"></WithInput>
</div>

// examples/vue/src/views/Uploader/index.vue
<template>
  <div class="responsive">
    <select-file></select-file>
    <canvas-element></canvas-element>
    <with-input fileFormat="File"></with-input>
    <with-input fileFormat="Blob"></with-input>
    <with-input fileFormat="Base64"></with-input>
    <with-input fileFormat="ArrayBuffer"></with-input>
  </div>
</template>

<script setup>
import CanvasElement from './Canvas';
import SelectFile from './SelectFile';
import WithInput from './WithInput';
</script>
