// examples/svelte/src/views/FormSubmit.svelte
<script>
  import { useRequest } from 'alova/client';
  import { addFruit } from '../api/methods';
  import { showToast } from '../helper';

  let fruit = '';
  const fruitsList = [];
  const {
    loading: submiting,
    error,
    send
  } = useRequest(() => addFruit(fruit), {
    immediate: false
  }).onSuccess(({ data }) => {
    fruitsList.push(data.added);
    fruit = '';
  });

  const submitFruit = () => {
    if (!fruit) {
      showToast('Please input a fruit');
      return;
    }
    send();
  };
</script>

<div class="flex flex-col items-start">
  <div class="flex flex-row items-end">
    <!-- svelte-ignore invalid-binding -->
    <nord-input
      label="What is your favorite fruits?"
      value={fruit}
      on:input={({ target }) => (fruit = target.value)} />
    <nord-button
      class="ml-2"
      variant="primary"
      loading={$submiting || undefined}
      on:click={submitFruit}>
      Submit
    </nord-button>
  </div>
  {#if $error}
    <span class="text-red-500">{$error.message}</span>
  {/if}

  <div class="mt-4 grid grid-cols-[repeat(8,fit-content(100px))] gap-2">
    {#each fruitsList as item}
      <nord-badge variant="success">{item}</nord-badge>
    {/each}
  </div>
</div>

// examples/vue/src/views/FormSubmit.vue
<template>
  <div class="flex flex-col items-start">
    <div class="flex flex-row items-end">
      <nord-input
        label="What is your favorite fruits?"
        v-model="fruit"></nord-input>
      <nord-button
        class="ml-2"
        variant="primary"
        :loading="submiting || undefined"
        @click="submitFruit">
        Submit
      </nord-button>
    </div>
    <span
      v-if="error"
      class="text-red-500"
      >{{ error.message }}</span
    >

    <div class="mt-4 grid grid-cols-[repeat(8,fit-content(100px))] gap-2">
      <nord-badge
        v-for="item in fruitsList"
        :key="item"
        variant="success">
        {{ item }}
      </nord-badge>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRequest } from 'alova/client';
import { addFruit } from '../api/methods';
import { showToast } from '../helper';

const fruit = ref('');
const fruitsList = ref([]);

const {
  loading: submiting,
  error,
  send
} = useRequest(() => addFruit(fruit.value), {
  immediate: false
}).onSuccess(({ data }) => {
  fruitsList.value = [...fruitsList.value, data.added];
  fruit.value = '';
});

const submitFruit = () => {
  if (!fruit.value) {
    showToast('Please input a fruit');
    return;
  }
  send();
};
</script>
