// examples/react/src/components/QueueConsole.jsx
import { onSilentSubmitError, onSilentSubmitFail, silentQueueMap } from 'alova/client';
import PropTypes from 'prop-types';
import { useEffect, useState } from 'react';
import { showToast } from '../helper';

const useWaitingSilentQueue = queueName => {
  const [waitingSilentQueue, setWaitingSilentQueue] = useState([]);
  useEffect(() => {
    // 修改队列为可监听的队列
    const customQueue = [];
    const originalPush = customQueue.push;
    const originalShift = customQueue.shift;
    customQueue.push = function (...items) {
      waitingSilentQueue.push(...items);
      setWaitingSilentQueue([...waitingSilentQueue]);
      return originalPush.call(this, ...items);
    };
    customQueue.shift = function () {
      const silentMethodInstance = originalShift.call(this);
      waitingSilentQueue.shift();
      setWaitingSilentQueue([...waitingSilentQueue]);
      return silentMethodInstance;
    };
    silentQueueMap[queueName] = customQueue;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return {
    queue: waitingSilentQueue,
    queueName
  };
};

function QueueConsole({ onModeChange, queueName }) {
  const [networkMode, setNetworkMode] = useState(0);
  const defaultWaitingSilentQueue = useWaitingSilentQueue(queueName);

  // 静默提交，多次重试后失败
  const [silentRequestError, setSilentRequestError] = useState('');
  useEffect(() => {
    const offSubmitError = onSilentSubmitError(event => {
      console.error(event.error);
      showToast(
        `Request Error: ${event.error}` + (event.retryDelay ? `, ${event.retryDelay / 1000}s after will retry` : ''),
        {
          variant: 'error'
        }
      );
    });
    const offSubmitFail = onSilentSubmitFail(event => {
      setSilentRequestError(event.error);
      showToast('Reach max retry times, but you can still operate it', {
        variant: 'error'
      });
    });
    onModeChange(networkMode);
    return () => {
      offSubmitError();
      offSubmitFail();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <nord-card>
      <label
        slot="header"
        className="text-lg font-bold mr-2">
        Network Mode
      </label>
      <nord-select
        slot="header-end"
        value={networkMode}
        hide-label
        onInput={({ target }) => {
          const value = Number(target.value);
          setNetworkMode(value);
          onModeChange(value);
        }}>
        <option value={0}>Silent Request</option>
        <option value={1}>Normal Request</option>
      </nord-select>
      <div className="border-b-[1px] last:border-b-0 pb-4 border-slate-200">
        {[defaultWaitingSilentQueue].map(({ queue, queueName }) => (
          <div key={queueName}>
            <div className="text-base font-semibold mb-2">Background Request Queue[{queueName}]</div>
            <div className="grid gap-y-4">
              {queue.map((sm, i) => (
                <div
                  key={sm.id}
                  className="border-2 border-slate-200 rounded-md px-3 py-2 flex items-center justify-between">
                  {!silentRequestError || i > 0 ? (
                    <div className="flex items-center">
                      <div className="mr-1">
                        {i > 0 ? <div className="bg-amber-400 w-2 h-2 rounded-lg"></div> : <nord-spinner />}
                      </div>
                      <span>{i > 0 ? 'waiting' : 'acting'}</span>
                    </div>
                  ) : (
                    <div className="flex items-center">
                      <div className="text-red-600 mr-1">×</div>
                      Request Error
                    </div>
                  )}
                  <span>
                    [{sm.entity.type}]{sm.entity.url}
                  </span>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    </nord-card>
  );
}
QueueConsole.propTypes = {
  queueName: PropTypes.string.isRequired,
  onModeChange: PropTypes.func.isRequired
};
export default QueueConsole;

// examples/solid/src/components/QueueConsole.jsx
import { onSilentSubmitError, onSilentSubmitFail, silentQueueMap } from 'alova/client';
import { createSignal, For, onCleanup, onMount } from 'solid-js';
import { showToast } from '../helper';

const useWaitingSilentQueue = queueName => {
  const [waitingSilentQueue, setWaitingSilentQueue] = createSignal([]);

  // 修改队列为可监听的队列
  const customQueue = [];
  const originalPush = customQueue.push;
  const originalShift = customQueue.shift;

  // eslint-disable-next-line
  customQueue.push = function (...items) {
    const updatedQueue = [...waitingSilentQueue(), ...items];
    setWaitingSilentQueue(updatedQueue);
    return originalPush.apply(this, items);
  };
  // eslint-disable-next-line
  customQueue.shift = function () {
    const silentMethodInstance = originalShift.call(this);
    setWaitingSilentQueue(waitingSilentQueue().slice(1));
    return silentMethodInstance;
  };

  silentQueueMap[queueName] = customQueue;

  return {
    queue: waitingSilentQueue,
    queueName
  };
};

function QueueConsole(props) {
  const [networkMode, setNetworkMode] = createSignal(0);
  const [silentRequestError, setSilentRequestError] = createSignal('');
  const defaultWaitingSilentQueue = useWaitingSilentQueue(props.queueName);

  // 静默提交，多次重试后失败
  onMount(() => {
    const offSubmitError = onSilentSubmitError(event => {
      console.error(event.error);
      showToast(
        `Request Error: ${event.error}` + (event.retryDelay ? `, ${event.retryDelay / 1000}s after will retry` : ''),
        {
          variant: 'error'
        }
      );
    });

    const offSubmitFail = onSilentSubmitFail(event => {
      setSilentRequestError(event.error);
      showToast('Reach max retry times, but you can still operate it', {
        variant: 'error'
      });
    });

    props.onModeChange(networkMode());

    // Cleanup on component unmount
    onCleanup(() => {
      offSubmitError();
      offSubmitFail();
    });
  });

  return (
    <nord-card>
      <label
        slot="header"
        class="text-lg font-bold mr-2">
        Network Mode
      </label>
      <nord-select
        slot="header-end"
        value={networkMode()}
        hide-label
        onInput={e => {
          const value = Number(e.target.value);
          setNetworkMode(value);
          props.onModeChange(value);
        }}>
        <option value={0}>Silent Request</option>
        <option value={1}>Normal Request</option>
      </nord-select>

      <div class="border-b-[1px] last:border-b-0 pb-4 border-slate-200">
        <For each={[defaultWaitingSilentQueue]}>
          {({ queue, queueName }) => (
            <div>
              <div class="text-base font-semibold mb-2">Background Request Queue[{queueName}]</div>
              <div class="grid gap-y-4">
                <For each={queue()}>
                  {(sm, i) => (
                    <div class="border-2 border-slate-200 rounded-md px-3 py-2 flex items-center justify-between">
                      {silentRequestError() === '' || i() > 0 ? (
                        <div class="flex items-center">
                          <div class="mr-1">
                            {i() > 0 ? <div class="bg-amber-400 w-2 h-2 rounded-lg" /> : <nord-spinner />}
                          </div>
                          <span>{i() > 0 ? 'waiting' : 'acting'}</span>
                        </div>
                      ) : (
                        <div class="flex items-center">
                          <div class="text-red-600 mr-1">×</div>
                          Request Error
                        </div>
                      )}
                      <span>
                        [{sm.entity.type}]{sm.entity.url}
                      </span>
                    </div>
                  )}
                </For>
              </div>
            </div>
          )}
        </For>
      </div>
    </nord-card>
  );
}

export default QueueConsole;
