// examples/vue/src/views/InitPage.vue
<template>
  <div>
    <nord-spinner
      v-if="loading"
      size="s" />
    <div v-else-if="error">{{ error.message }}</div>
    <div
      v-else
      class="grid grid-cols-[repeat(8,fit-content(100px))] gap-2">
      <nord-badge
        v-for="item in data"
        :key="item"
        class="mr-2"
        variant="success">
        {{ item }}
      </nord-badge>
    </div>
  </div>
</template>

<script setup>
import { useRequest } from 'alova/client';
import { getData } from '../api/methods';

const { data, loading, error } = useRequest(getData, {
  initialData: []
});
</script>

// examples/react/src/views/InitPage.jsx
import { useRequest } from 'alova/client';
import { getData } from '../api/methods';

function View() {
  const { data, loading, error } = useRequest(getData, {
    initialData: []
  });

  if (loading) {
    return <nord-spinner size="s" />;
  } else if (error) {
    return <div>{error.message}</div>;
  }
  return (
    <div className="grid grid-cols-[repeat(8,fit-content(100px))] gap-2">
      {data.map(item => (
        <nord-badge
          key={item}
          class="mr-2"
          variant="success">
          {item}
        </nord-badge>
      ))}
    </div>
  );
}

export default View;
