// examples/vue/src/components/Table.vue
<template>
  <nord-card
    padding="none"
    class="relative">
    <div
      v-if="loading"
      class="absolute top-0 left-0 right-0 bottom-0 bg-gray-600 bg-opacity-30 z-10 flex items-center justify-center">
      <nord-spinner></nord-spinner>
    </div>
    <h3
      v-if="title"
      class="text-lg"
      slot="header">
      {{ title }}
    </h3>
    <nord-table :style="style">
      <table>
        <thead>
          <tr>
            <th
              v-for="{ title, dataIndex } in columns"
              :key="dataIndex">
              {{ title }}
            </th>
          </tr>
        </thead>
        <tbody>
          <template v-if="data.length > 0">
            <tr
              v-for="(row, index) in data"
              :key="index"
              v-bind="rowProps ? rowProps(row, index) : {}">
              <td
                v-for="{ dataIndex, render } in columns"
                :key="dataIndex">
                <component
                  v-if="typeof render === 'function'"
                  :is="render(row[dataIndex], row)"
                  :row="row"
                  :index="index">
                </component>
                <template v-else>
                  {{ row[dataIndex] }}
                </template>
              </td>
            </tr>
          </template>
          <tr v-else>
            <td :colspan="columns.length">No Data</td>
          </tr>
        </tbody>
      </table>
    </nord-table>

    <nord-stack
      v-if="pagination"
      direction="horizontal"
      align-items="center"
      role="list"
      class="p-4">
      <nord-button
        v-if="pagination.page > 1"
        role="listitem"
        @click="pagination.onChange(pagination.page - 1, pagination.pageSize)">
        <nord-icon
          name="arrow-left-small"
          label="Previous"></nord-icon>
      </nord-button>
      <p
        v-if="pagination.page > 5"
        class="n-padding-i-m n-color-text-weaker"
        aria-hidden="true">
        …
      </p>

      <nord-button
        v-for="pageNumber in getPageList(pagination.page, pagination.pageCount)"
        :key="pageNumber"
        @click="pagination.onChange(pageNumber, pagination.pageSize)"
        role="listitem"
        :variant="pageNumber === pagination.page ? 'primary' : 'plain'">
        {{ pageNumber }}
      </nord-button>

      <p
        v-if="pagination.pageCount - pagination.page > 5"
        class="n-padding-i-m n-color-text-weaker"
        aria-hidden="true">
        …
      </p>
      <nord-button
        v-if="pagination.page < pagination.pageCount"
        role="listitem"
        @click="pagination.onChange(pagination.page + 1, pagination.pageSize)">
        <nord-icon
          name="arrow-right-small"
          label="Next"></nord-icon>
      </nord-button>

      <nord-select
        v-if="pagination.pageSizes"
        hide-label
        :value="pagination.pageSize"
        @input="event => pagination.onChange(pagination.page, event.target.value)">
        <option
          v-for="size in pagination.pageSizes"
          :key="size"
          :value="size">
          {{ size }} items/page
        </option>
      </nord-select>
      <nord-button
        v-if="pagination.total"
        disabled
        >Total: {{ pagination.total }}</nord-button
      >
    </nord-stack>
  </nord-card>
</template>

<script setup>
import { defineProps } from 'vue';

const props = defineProps({
  style: Object,
  loading: Boolean,
  columns: {
    type: Array,
    required: true,
    validator: value => value.every(col => 'title' in col && 'dataIndex' in col)
  },
  data: {
    type: Array,
    required: true
  },
  title: String,
  rowProps: Function,
  pagination: Object
});

const getPageList = (page, pageCount) => {
  const start = Math.max(page - 2, 1);
  const end = Math.min(start + 4, pageCount);
  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
};
</script>

// examples/react/src/components/Table.jsx
import PropTypes from 'prop-types';

function Table({ style = {}, columns, data, loading, title, rowProps, pagination }) {
  const getPageList = (page, pageCount) => {
    const start = Math.max(page - 2, 1);
    const end = Math.min(start + 4, pageCount);
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  };

  return (
    <nord-card
      padding="none"
      class="relative">
      {loading ? (
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-gray-600 bg-opacity-30 z-10 flex items-center justify-center">
          <nord-spinner></nord-spinner>
        </div>
      ) : null}
      {title ? (
        <h3
          className="text-lg"
          slot="header">
          {title}
        </h3>
      ) : null}
      <nord-table style={style}>
        <table>
          <thead>
            <tr>
              {columns.map(({ title, dataIndex }) => (
                <th key={dataIndex}>{title}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.length > 0 ? (
              data.map((row, index) => {
                const { onClick, style } = rowProps ? rowProps(row, index) : {};
                return (
                  <tr
                    key={index}
                    style={style}
                    onClick={onClick}>
                    {columns.map(({ dataIndex, render }) => (
                      <td key={dataIndex}>
                        {typeof render === 'function' ? render(row[dataIndex], row) : row[dataIndex]}
                      </td>
                    ))}
                  </tr>
                );
              })
            ) : (
              <tr>
                <td colSpan={columns.length}>No Data</td>
              </tr>
            )}
          </tbody>
        </table>
      </nord-table>

      {pagination ? (
        <nord-stack
          direction="horizontal"
          align-items="center"
          role="list"
          class="p-4">
          {pagination.page > 1 ? (
            <nord-button
              role="listitem"
              onClick={() => pagination.onChange(pagination.page - 1, pagination.pageSize)}>
              <nord-icon
                name="arrow-left-small"
                label="Previous"></nord-icon>
            </nord-button>
          ) : null}
          {pagination.page > 5 ? (
            <p
              className="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          ) : null}

          {getPageList(pagination.page, pagination.pageCount).map(pageNumber => (
            <nord-button
              onClick={() => pagination.onChange(pageNumber, pagination.pageSize)}
              key={pageNumber}
              role="listitem"
              variant={pageNumber === pagination.page ? 'primary' : 'plain'}>
              {pageNumber}
            </nord-button>
          ))}
          {pagination.pageCount - pagination.page > 5 ? (
            <p
              className="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          ) : null}
          {pagination.page < pagination.pageCount ? (
            <nord-button
              role="listitem"
              onClick={() => pagination.onChange(pagination.page + 1, pagination.pageSize)}>
              <nord-icon
                name="arrow-right-small"
                label="Next"></nord-icon>
            </nord-button>
          ) : null}

          {pagination.pageSizes ? (
            <nord-select
              hide-label
              value={pagination.pageSize}
              onInput={({ target }) => pagination.onChange(pagination.page, target.value)}>
              {pagination.pageSizes.map(size => (
                <option
                  key={size}
                  value={size}>
                  {size} items/page
                </option>
              ))}
            </nord-select>
          ) : null}
          {pagination.total ? <nord-button disabled>Total: {pagination.total}</nord-button> : null}
        </nord-stack>
      ) : null}
    </nord-card>
  );
}

Table.propTypes = {
  style: PropTypes.object,
  loading: PropTypes.bool,
  columns: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string.isRequired,
      dataIndex: PropTypes.string.isRequired,
      render: PropTypes.func
    })
  ).isRequired,
  data: PropTypes.arrayOf(PropTypes.object).isRequired,
  title: PropTypes.string,
  rowProps: PropTypes.func,
  pagination: PropTypes.object
};

export default Table;
