// examples/solid/src/components/Table.jsx
import { createMemo, For, mergeProps, Show } from 'solid-js';

function Table(_props) {
  const props = mergeProps({ style: {} }, _props);

  const pageList = createMemo(() => {
    const { page, pageCount } = props.pagination || {};
    if (!page || !pageCount) {
      return [];
    }

    const start = Math.max(page() - 2, 1);
    const end = Math.min(start + 4, pageCount());
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  });

  return (
    <nord-card
      padding="none"
      class="relative">
      <Show when={props.loading}>
        <div class="absolute top-0 left-0 right-0 bottom-0 bg-gray-600 bg-opacity-30 z-10 flex items-center justify-center">
          <nord-spinner />
        </div>
      </Show>
      <Show when={props.title}>
        <h3
          class="text-lg"
          slot="header">
          {props.title}
        </h3>
      </Show>
      <nord-table style={props.style}>
        <table>
          <thead>
            <tr>
              <For each={props.columns}>{({ title }) => <th>{title}</th>}</For>
            </tr>
          </thead>
          <tbody>
            <Show
              when={props.data.length > 0}
              fallback={
                <tr>
                  <td colSpan={props.columns.length}>No Data</td>
                </tr>
              }>
              <For each={props.data}>
                {(row, index) => {
                  const componentProps = props.rowProps ? props.rowProps(row, index()) : {};
                  return (
                    <tr {...componentProps}>
                      <For each={props.columns}>
                        {({ dataIndex, render }) => (
                          <td>
                            {typeof render === 'function' ? render(row[dataIndex], row, index()) : row[dataIndex]}
                          </td>
                        )}
                      </For>
                    </tr>
                  );
                }}
              </For>
            </Show>
          </tbody>
        </table>
      </nord-table>
      <Show when={props.pagination}>
        <nord-stack
          direction="horizontal"
          align-items="center"
          role="list"
          class="p-4">
          <nord-button
            disabled={props.pagination.page <= 1}
            role="listitem"
            onClick={() => props.pagination.onChange(props.pagination.page - 1, props.pagination.pageSize)}>
            <nord-icon
              name="arrow-left-small"
              label="Previous"
            />
          </nord-button>
          <Show when={props.pagination.page() > 5}>
            <p
              class="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          </Show>
          <For each={pageList()}>
            {pageNumber => (
              <nord-button
                onClick={() => props.pagination.onChange(pageNumber, props.pagination.pageSize)}
                role="listitem"
                variant={pageNumber === props.pagination.page() ? 'primary' : 'plain'}>
                {pageNumber}
              </nord-button>
            )}
          </For>
          <Show when={props.pagination.pageCount - props.pagination.page > 5}>
            <p
              class="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          </Show>
          <nord-button
            disabled={props.pagination.page >= props.pagination.pageCount}
            role="listitem"
            onClick={() => props.pagination.onChange(props.pagination.page + 1, props.pagination.pageSize)}>
            <nord-icon
              name="arrow-right-small"
              label="Next"
            />
          </nord-button>
          <Show when={props.pagination.pageSizes}>
            <nord-select
              hide-label
              value={props.pagination.pageSize}
              onInput={e => props.pagination.onChange(props.pagination.page, e.target.value)}>
              <For each={props.pagination.pageSizes}>{size => <option value={size}>{size} items/page</option>}</For>
            </nord-select>
          </Show>
          <Show when={props.pagination.total}>
            <nord-button disabled>Total: {props.pagination.total}</nord-button>
          </Show>
        </nord-stack>
      </Show>
    </nord-card>
  );
}

export default Table;

// examples/react/src/components/Table.jsx
import PropTypes from 'prop-types';

function Table({ style = {}, columns, data, loading, title, rowProps, pagination }) {
  const getPageList = (page, pageCount) => {
    const start = Math.max(page - 2, 1);
    const end = Math.min(start + 4, pageCount);
    return Array.from({ length: end - start + 1 }, (_, i) => start + i);
  };

  return (
    <nord-card
      padding="none"
      class="relative">
      {loading ? (
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-gray-600 bg-opacity-30 z-10 flex items-center justify-center">
          <nord-spinner></nord-spinner>
        </div>
      ) : null}
      {title ? (
        <h3
          className="text-lg"
          slot="header">
          {title}
        </h3>
      ) : null}
      <nord-table style={style}>
        <table>
          <thead>
            <tr>
              {columns.map(({ title, dataIndex }) => (
                <th key={dataIndex}>{title}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {data.length > 0 ? (
              data.map((row, index) => {
                const { onClick, style } = rowProps ? rowProps(row, index) : {};
                return (
                  <tr
                    key={index}
                    style={style}
                    onClick={onClick}>
                    {columns.map(({ dataIndex, render }) => (
                      <td key={dataIndex}>
                        {typeof render === 'function' ? render(row[dataIndex], row) : row[dataIndex]}
                      </td>
                    ))}
                  </tr>
                );
              })
            ) : (
              <tr>
                <td colSpan={columns.length}>No Data</td>
              </tr>
            )}
          </tbody>
        </table>
      </nord-table>

      {pagination ? (
        <nord-stack
          direction="horizontal"
          align-items="center"
          role="list"
          class="p-4">
          {pagination.page > 1 ? (
            <nord-button
              role="listitem"
              onClick={() => pagination.onChange(pagination.page - 1, pagination.pageSize)}>
              <nord-icon
                name="arrow-left-small"
                label="Previous"></nord-icon>
            </nord-button>
          ) : null}
          {pagination.page > 5 ? (
            <p
              className="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          ) : null}

          {getPageList(pagination.page, pagination.pageCount).map(pageNumber => (
            <nord-button
              onClick={() => pagination.onChange(pageNumber, pagination.pageSize)}
              key={pageNumber}
              role="listitem"
              variant={pageNumber === pagination.page ? 'primary' : 'plain'}>
              {pageNumber}
            </nord-button>
          ))}
          {pagination.pageCount - pagination.page > 5 ? (
            <p
              className="n-padding-i-m n-color-text-weaker"
              aria-hidden="true">
              …
            </p>
          ) : null}
          {pagination.page < pagination.pageCount ? (
            <nord-button
              role="listitem"
              onClick={() => pagination.onChange(pagination.page + 1, pagination.pageSize)}>
              <nord-icon
                name="arrow-right-small"
                label="Next"></nord-icon>
            </nord-button>
          ) : null}

          {pagination.pageSizes ? (
            <nord-select
              hide-label
              value={pagination.pageSize}
              onInput={({ target }) => pagination.onChange(pagination.page, target.value)}>
              {pagination.pageSizes.map(size => (
                <option
                  key={size}
                  value={size}>
                  {size} items/page
                </option>
              ))}
            </nord-select>
          ) : null}
          {pagination.total ? <nord-button disabled>Total: {pagination.total}</nord-button> : null}
        </nord-stack>
      ) : null}
    </nord-card>
  );
}

Table.propTypes = {
  style: PropTypes.object,
  loading: PropTypes.bool,
  columns: PropTypes.arrayOf(
    PropTypes.shape({
      title: PropTypes.string.isRequired,
      dataIndex: PropTypes.string.isRequired,
      render: PropTypes.func
    })
  ).isRequired,
  data: PropTypes.arrayOf(PropTypes.object).isRequired,
  title: PropTypes.string,
  rowProps: PropTypes.func,
  pagination: PropTypes.object
};

export default Table;
