// examples/react/src/views/RetriableRequest/index.jsx
import Implementation from './Implementation';

function View() {
  return (
    <div
      className="responsive"
      style={{ alignItems: 'stretch' }}>
      <Implementation id="a"></Implementation>
      <Implementation id="b"></Implementation>
      <Implementation id="c"></Implementation>
      <Implementation id="d"></Implementation>
      <Implementation id="e"></Implementation>
    </div>
  );
}

export default View;

// examples/svelte/src/views/RetriableRequest/index.vue
<template>
  <div
    class="responsive"
    style="align-items: stretch">
    <implementation id="a" />
    <implementation id="b" />
    <implementation id="c" />
    <implementation id="d" />
    <implementation id="e" />
  </div>
</template>

<script setup>
import Implementation from './Implementation.vue';
</script>
